apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: sec-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: sec-app
        image: ghcr.io/andrewkreuzer/sec-app:main-4deac0f2-2192313301
        ports:
        - containerPort: 80
