apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-app
  namespace: sec-app
spec:
  selector:
    matchLabels:
      app: sec-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sec-app
    spec:
      containers:
      - name: sec-app
        image: ghcr.io/andrewkreuzer/sec-app:main-4deac0f2-2192313301 # {"$imagepolicy": "flux-system:sec-app"}
        ports:
        - containerPort: 80
